# Generated by Django 5.0.6 on 2024-06-24 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0003_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='empoyee_name',
            new_name='employee_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='other_benifits',
            new_name='other_benefits',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='total_benifits',
            new_name='total_benefits',
        ),
    ]
